micronaut:
  application:
    name: mnQuickstart
  server:
    port: ${SERVER_PORT:8080}
hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Walt"
      en: "Hello World"